### ISSUE TITLE
Drupal `pm-updatecode` will Replace .htaccess and robots.txt Customizations

### ISSUE THREAD

**Issue by seth-reeser** [devopsgroup-io/catapult#811]
Consider an `_append` folder in the repo root that accepts defined files for appending.

Considerations to take into account:
* Cross-software solution
* How to keep track of the append - some sort of marker and diff the contents?
````
# CATAPULT APPEND START
...
# CATAPULT APPEND END
````

For context, current folders include:
* `_sql`
* `_cert`

**Comment by stevebritton** [comment]
Please note that `pm-updatecode` will also replace robots.txt customizations.

**Comment by seth-reeser** [comment]
Solved with https://github.com/devopsgroup-io/catapult/pull/841/files
